### ISSUE TITLE
Build/test problems on openSUSE

### ISSUE THREAD

**Issue by weberhofer** [systemd/python-systemd#12]
With the current release 231, some tests fail within the build-environment. Do you have any hint how to solve that?
```
[   23s] + make -j8 check
[   23s] /bin/sh: git: command not found
[   23s] python setup.py build
[   23s] running build
[   23s] running build_py
[   23s] package init file 'systemd/test/__init__.py' not found (or not a regular file)
[   23s] package init file 'systemd/test/__init__.py' not found (or not a regular file)
[   23s] running build_ext
[   23s] (cd build/lib.linux-x86_64-2.7 && python -m py.test . ../../docs -v)
[   23s] ============================= test session starts ==============================
[   23s] platform linux2 -- Python 2.7.9, pytest-2.8.2, py-1.4.30, pluggy-0.3.1 -- /usr/bin/python
[   23s] cachedir: ../../.cache
[   23s] rootdir: /home/abuild/rpmbuild/BUILD/python-systemd-231, inifile: pytest.ini
[   23s] collecting ... collected 38 items
[   23s] 
[   23s] systemd/journal.py::systemd.journal.JournalHandler PASSED
[   23s] systemd/journal.py::systemd.journal.Reader PASSED
[   23s] systemd/journal.py::systemd.journal.send PASSED
[   23s] systemd/journal.py::systemd.journal.stream FAILED
[   23s] systemd/test/test_daemon.py::test_booted PASSED
[   23s] systemd/test/test_daemon.py::test__is_fifo PASSED
[   23s] systemd/test/test_daemon.py::test__is_fifo_file PASSED
[   23s] systemd/test/test_daemon.py::test__is_fifo_bad_fd PASSED
[   23s] systemd/test/test_daemon.py::test_is_fifo PASSED
[   23s] systemd/test/test_daemon.py::test_is_fifo_file PASSED
[   23s] systemd/test/test_daemon.py::test_is_fifo_bad_fd PASSED
[   23s] systemd/test/test_daemon.py::test_no_mismatch PASSED
[   23s] systemd/test/test_daemon.py::test_is_socket PASSED
[   23s] systemd/test/test_daemon.py::test__is_socket PASSED
[   23s] systemd/test/test_daemon.py::test_is_socket_unix PASSED
[   23s] systemd/test/test_daemon.py::test__is_socket_unix PASSED
[   23s] systemd/test/test_daemon.py::test_listen_fds_no_fds PASSED
[   23s] systemd/test/test_daemon.py::test_listen_fds PASSED
[   23s] systemd/test/test_daemon.py::test_listen_fds_default_unset PASSED
[   24s] systemd/test/test_daemon.py::test_notify_no_socket FAILED
[   24s] systemd/test/test_daemon.py::test_notify_bad_socket FAILED
[   24s] systemd/test/test_daemon.py::test_notify_with_socket FAILED
[   24s] systemd/test/test_journal.py::test_priorities PASSED
[   24s] systemd/test/test_journal.py::test_journalhandler_init_exception PASSED
[   24s] systemd/test/test_journal.py::test_journalhandler_init PASSED
[   24s] systemd/test/test_journal.py::test_reader_init_flags PASSED
[   24s] systemd/test/test_journal.py::test_reader_init_path PASSED
[   24s] systemd/test/test_journal.py::test_reader_as_cm PASSED
[   24s] systemd/test/test_journal.py::test_reader_messageid_match PASSED
[   24s] systemd/test/test_journal.py::test_reader_this_boot PASSED
[   24s] systemd/test/test_journal.py::test_reader_this_machine PASSED
[   24s] systemd/test/test_journal.py::test_reader_converters PASSED
[   24s] systemd/test/test_journal.py::test_reader_convert_entry PASSED
[   24s] ../../docs/daemon.rst SKIPPED
[   24s] ../../docs/id128.rst SKIPPED
[   24s] ../../docs/index.rst SKIPPED
[   24s] ../../docs/journal.rst PASSED
[   24s] ../../docs/login.rst FAILED
[   24s] 
[   24s] =================================== FAILURES ===================================
[   24s] _______________________ [doctest] systemd.journal.stream _______________________
[   24s] 414     r"""Return a file object wrapping a stream to journal.
[   24s] 415 
[   24s] 416     Log messages written to this file as simple newline sepearted text
[   24s] 417     strings are written to the journal.
[   24s] 418 
[   24s] 419     The file will be line buffered, so messages are actually sent
[   24s] 420     after a newline character is written.
[   24s] 421 
[   24s] 422     >>> from systemd import journal
[   24s] 423     >>> stream = journal.stream('myapp')
[   24s] UNEXPECTED EXCEPTION: IOError(2, 'No such file or directory')
[   24s] Traceback (most recent call last):
[   24s] 
[   24s]   File "/usr/lib64/python2.7/doctest.py", line 1315, in __run
[   24s]     compileflags, 1) in test.globs
[   24s] 
[   24s]   File "<doctest systemd.journal.stream[1]>", line 1, in <module>
[   24s] 
[   24s]   File "/home/abuild/rpmbuild/BUILD/python-systemd-231/build/lib.linux-x86_64-2.7/systemd/journal.py", line 446, in stream
[   24s]     fd = stream_fd(identifier, priority, level_prefix)
[   24s] 
[   24s] IOError: [Errno 2] No such file or directory
[   24s] 
[   24s] /home/abuild/rpmbuild/BUILD/python-systemd-231/build/lib.linux-x86_64-2.7/systemd/journal.py:423: UnexpectedException
[   24s] ____________________________ test_notify_no_socket _____________________________
[   24s] 
[   24s]     def test_notify_no_socket():
[   24s]         assert notify('READY=1') == False
[   24s] >       assert notify('FDSTORE=1', fds=[]) == False
[   24s] E       NotImplementedError: Compiled without support for sd_pid_notify_with_fds
[   24s] 
[   24s] systemd/test/test_daemon.py:203: NotImplementedError
[   24s] ____________________________ test_notify_bad_socket ____________________________
[   24s] 
[   24s]     def test_notify_bad_socket():
[   24s]         os.environ['NOTIFY_SOCKET'] = '/dev/null'
[   24s]     
[   24s]         with pytest.raises(connection_error):
[   24s]             notify('READY=1')
[   24s]         with pytest.raises(connection_error):
[   24s] >           notify('FDSTORE=1', fds=[])
[   24s] E           NotImplementedError: Compiled without support for sd_pid_notify_with_fds
[   24s] 
[   24s] systemd/test/test_daemon.py:219: NotImplementedError
[   24s] ___________________________ test_notify_with_socket ____________________________
[   24s] 
[   24s] tmpdir = local('/tmp/pytest-of-abuild/pytest-2/test_notify_with_socket0')
[   24s] 
[   24s]     def test_notify_with_socket(tmpdir):
[   24s]         path = tmpdir.join('socket').strpath
[   24s]         sock = socket.socket(socket.AF_UNIX, socket.SOCK_DGRAM)
[   24s]         sock.bind(path)
[   24s] >       sock.setsockopt(socket.SOL_SOCKET, socket.SO_PASSCRED, 1)
[   24s] E       AttributeError: 'module' object has no attribute 'SO_PASSCRED'
[   24s] 
[   24s] systemd/test/test_daemon.py:231: AttributeError
[   24s] ___________________________ [doctest] docs/login.rst ___________________________
[   24s] 011 Example: polling for events
[   24s] 012 ~~~~~~~~~~~~~~~~~~~~~~~~~~~
[   24s] 013 
[   24s] 014 This example shows that session/uid/seat/machine events can be waited
[   24s] 015 for (using e.g. `poll`). This makes it easy to integrate Monitor in an
[   24s] 016 external event loop:
[   24s] 017 
[   24s] 018   >>> import select
[   24s] 019   >>> from systemd import login
[   24s] 020   >>> m = login.Monitor("machine")
[   24s] UNEXPECTED EXCEPTION: OSError(2, 'No such file or directory')
[   24s] Traceback (most recent call last):
[   24s] 
[   24s]   File "/usr/lib64/python2.7/doctest.py", line 1315, in __run
[   24s]     compileflags, 1) in test.globs
[   24s] 
[   24s]   File "<doctest login.rst[2]>", line 1, in <module>
[   24s] 
[   24s] OSError: [Errno 2] No such file or directory
[   24s] 
[   24s] /home/abuild/rpmbuild/BUILD/python-systemd-231/docs/login.rst:20: UnexpectedException
[   24s] ================ 5 failed, 30 passed, 3 skipped in 0.29 seconds ================
[   24s] Makefile:39: recipe for target 'check' failed
[   24s] make: *** [check] Error 1
[   24s] error: Bad exit status from /var/tmp/rpm-tmp.mi76ss (%check)
```
Additionally, there are two compiler-notes I see during compilation:
```
[   20s] systemd/_reader.c: In function 'Reader_next':
[   20s] systemd/_reader.c:360:22: warning: 'r' may be used uninitialized in this function [-Wmaybe-uninitialized]
[   20s]          if (set_error(r, NULL, NULL) < 0)
```
```
[   20s] systemd/_daemon.c: In function 'notify':
[   20s] systemd/_daemon.c:79:28: warning: variable 'n_fds' set but not used [-Wunused-but-set-variable]
[   20s]          int unset = false, n_fds;
```

**Comment by keszybz** [comment]
>  systemd/_reader.c:360:22: warning: 'r' may be used uninitialized 

Yeah, gcc doesn't understand the if statement. I'll just add a dummy initializer to suppress this: c8749e7fbc.

> systemd/_daemon.c:79:28: warning: variable 'n_fds' set but not used

This only happens with old libsystemd. If somebody writes a patch for that, I can apply.

For the rest, someone should write skip conditions :)

**Comment by sebix** [comment]
I guess these problems are solved because it builds fine here (including running tests): https://build.opensuse.org/package/show/home:michalnowak/python3-systemd

**Comment by weberhofer** [comment]
T@sebix, the tests still fail, but 
```make PYTHON=/usr/bin/python3 %{?_smp_mflags} check || :```
makes the packaging proceed even when the tests fail...

**Comment by keszybz** [comment]
I added a skip wrapper for the test cases that failed in the OBS build log from @sebix's comment. If there's more things which need wrapping, it should be trivial to do.

**Comment by weberhofer** [comment]
@keszybz thanks! I'll test with the next release.
