### ISSUE TITLE
journal.Reader.add_match breaks on python>=3.10

### ISSUE THREAD

**Issue by Yamboy1** [systemd/python-systemd#122]
Minimal repro:
```py
from systemd import journal

j = journal.Reader()
j.add_match(_SYSTEMD_UNIT="httpd.service")
```
Error:
```
Traceback (most recent call last):
  File "/home/dobby/projectserver/./server.py", line 14, in <module>
    j.add_match(_SYSTEMD_UNIT="httpd.service")
  File "/home/dobby/.local/share/virtualenvs/server-dx5eltbR/lib64/python3.11/site-packages/systemd/journal.py", line 244, in add_match
    super(Reader, self).add_match(arg)
SystemError: PY_SSIZE_T_CLEAN macro must be defined for '#' formats
```
See python/cpython#85115 for more info.

**Comment by TitaniumHocker** [comment]
This is already fixed, see #107, but new release wasn't uploaded to PyPI, see #120

**Comment by TitaniumHocker** [comment]
I think this issue can be closed...

**Comment by calexandru2018** [comment]
I'm still experiencing this issue, when is the release happening ?

**Comment by TitaniumHocker** [comment]
@keszybz Are you alive?

**Comment by Guiorgy** [comment]
@Yamboy1, @TitaniumHocker, @calexandru2018 v235 has been published to [pypi](https://pypi.org/project/systemd-python/), this can be closed
